-- MySQL Script generated by MySQL Workbench
-- Thu May 15 17:34:41 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rental_fraud_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rental_fraud_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `rental_fraud_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rental_fraud_db`.`user` (
  `user_id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `birth_date` DATE NOT NULL,
  `social_login_type` VARCHAR(20) NULL DEFAULT NULL,
  `joined_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `role` ENUM('user', 'admin') NULL DEFAULT 'user',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `rental_fraud_db`.`insurance_recommendation_input`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rental_fraud_db`.`insurance_recommendation_input` (
  `recommendation_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(50) NULL DEFAULT NULL,
  `recommended_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `is_homeless` TINYINT(1) NULL DEFAULT 0,
  `deposit` INT(11) NOT NULL,
  `target_type` VARCHAR(20) NOT NULL,
  `income_level` VARCHAR(50) NOT NULL,
  `housing_type` VARCHAR(50) NOT NULL,
  `region` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`recommendation_id`),
  CONSTRAINT `insurance_recommendation_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `rental_fraud_db`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`insurance_recommendation_result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rental_fraud_db`.`insurance_recommendation_result` (
  `recommendation_id` INT(11) NOT NULL AUTO_INCREMENT,
  `insurance_company` VARCHAR(50) NULL,
  `guarantee_limit` INT NULL,
  `guarantee_fee` INT NULL,
  `is_eilgible` TINYINT(0) NULL DEFAULT 0,
  `required_document` TEXT NULL,
  PRIMARY KEY (`recommendation_id`),
  CONSTRAINT `fk_insurance_recommendation_result_insurance_recommendation_i`
    FOREIGN KEY (`recommendation_id`)
    REFERENCES `rental_fraud_db`.`insurance_recommendation_input` (`recommendation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `rental_fraud_db`.`checklist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rental_fraud_db`.`checklist` (
  `checklist_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(50) NULL DEFAULT NULL,
  `item` TEXT NOT NULL,
  `is_checked` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`checklist_id`),
  CONSTRAINT `checklist_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `rental_fraud_db`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `rental_fraud_db`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rental_fraud_db`.`post` (
  `post_id` INT(11) NOT NULL AUTO_INCREMENT,
  `author_id` VARCHAR(50) NULL DEFAULT NULL,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `region` VARCHAR(50) NULL DEFAULT NULL,
  `fraud_type` VARCHAR(50) NULL DEFAULT NULL,
  `contract_stage` ENUM('before', 'during', 'after') NULL DEFAULT NULL,
  `views` INT(11) NULL DEFAULT 0,
  PRIMARY KEY (`post_id`),
  CONSTRAINT `post_ibfk_1`
    FOREIGN KEY (`author_id`)
    REFERENCES `rental_fraud_db`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `rental_fraud_db`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rental_fraud_db`.`comment` (
  `comment_id` INT(11) NOT NULL AUTO_INCREMENT,
  `post_id` INT(11) NULL DEFAULT NULL,
  `author_id` VARCHAR(50) NULL DEFAULT NULL,
  `content` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`comment_id`),
  CONSTRAINT `comment_ibfk_1`
    FOREIGN KEY (`post_id`)
    REFERENCES `rental_fraud_db`.`post` (`post_id`),
  CONSTRAINT `comment_ibfk_2`
    FOREIGN KEY (`author_id`)
    REFERENCES `rental_fraud_db`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `rental_fraud_db`.`notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rental_fraud_db`.`notice` (
  `notice_id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `admin_id` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`notice_id`),
  CONSTRAINT `notice_ibfk_1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `rental_fraud_db`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `rental_fraud_db`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rental_fraud_db`.`report` (
  `report_id` INT(11) NOT NULL AUTO_INCREMENT,
  `post_id` INT(11) NULL DEFAULT NULL,
  `reporter_id` VARCHAR(50) NULL DEFAULT NULL,
  `reason` TEXT NOT NULL,
  `reported_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`report_id`),
  CONSTRAINT `report_ibfk_1`
    FOREIGN KEY (`post_id`)
    REFERENCES `rental_fraud_db`.`post` (`post_id`),
  CONSTRAINT `report_ibfk_2`
    FOREIGN KEY (`reporter_id`)
    REFERENCES `rental_fraud_db`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `rental_fraud_db`.`scrap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rental_fraud_db`.`scrap` (
  `post_id` INT(11) NOT NULL,
  `user_id` VARCHAR(50) NOT NULL,
  `scraped_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`post_id`, `user_id`),
  CONSTRAINT `scrap_ibfk_1`
    FOREIGN KEY (`post_id`)
    REFERENCES `rental_fraud_db`.`post` (`post_id`),
  CONSTRAINT `scrap_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `rental_fraud_db`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
